# device-mapper-multipath configuration file

# For a complete list of the default configuration values, run either:
# # multipath -t
# or
# # multipathd show config

# For a list of configuration options with descriptions, see the
# multipath.conf man page.
defaults {
user_friendly_names yes
find_multipaths yes
	  }

devices {
    device {
        vendor "COMPELNT"
        product "Compellent Vol"
        path_grouping_policy group_by_prio
        path_selector "round-robin 0"
        path_checker tur
        hardware_handler "1 alua"
        prio alua
        failback immediate
        rr_weight uniform
        no_path_retry queue
    }
}


multipaths {
        multipath {
                wwid    36000d310045504000000000000000034
                alias   ASM01
        }
	multipath {
                wwid    36000d310045504000000000000000035
                alias   ASM02
        }
	multipath {
                wwid    36000d310045504000000000000000036
                alias   ASM03
        }
	multipath {
                wwid    36000d310045504000000000000000037
                alias   ASM04
        }
	multipath {
                wwid    36000d310045504000000000000000038
                alias   ASM05
        }
	multipath {
                wwid    36000d310045504000000000000000039
                alias   ASM06
        }
	multipath {
                wwid   36000d31004550400000000000000003a
                alias  ASM07
        }
	multipath {
                wwid   36000d31004550400000000000000003b
                alias  ASM08 
        }
	multipath {
                wwid   36000d31004550400000000000000003c
                alias  ASM09 
        }
      
} 

